export const GET_RECEPIE_REQUEST = "GET_RECEPIE_REQUEST";
export const GET_RECEPIE_SUCCESS = "GET_RECEPIE_SUCCESS";
export const GET_RECEPIE_ERROR = "GET_RECEPIE_ERROR";



export const GET_RANDOM_RECEPIE_REQUEST = "GET_RANDOM_RECEPIE_REQUEST";
export const GET_RANDOM_RECEPIE_SUCCESS = "GET_RANDOM_RECEPIE_SUCCESS";
export const GET_RANDOM_RECEPIE_ERROR = "GET_RANDOM_RECEPIE_ERROR";


export const GET_RECEPIE_DETAIL_REQUEST = "GET_RECEPIE_DETAIL_REQUEST";
export const GET_RECEPIE_DETAIL_SUCCESS = "GET_RECEPIE_DETAIL_SUCCESS";
export const GET_RECEPIE_DETAIL_ERROR = "GET_RECEPIE_DETAIL_ERROR";